source 'https://rubygems.org'

gem 'sinatra', '~> 1.4'
gem 'thin',    '~> 1.6'

gem 'money',   '~> 6.5'

group :development do
  gem 'guard',          '~> 2.12'
  gem 'guard-minitest', '~> 2.4'
  gem 'guard-rubocop',  '~> 1.2'
  gem 'rubocop',        '~> 0.30', require: false
  gem 'factory_girl',   '~> 4.5'
end
